NET_IF_0="static 10.10.0.31 1"
#------------------------------------------------------------------------------
# Mgmt network (elevate interface boot priority to 1; set when PXE booting)
NET_IF_1="static 10.10.1.31 1"
# Public network (select network, IP address configured manually)
NET_IF_2="manual 203.0.113.0"

NET_IF_4=dhcp
#------------------------------------------------------------------------------
# Size of second disk in MB (/dev/sdb)
# Test volume is 1 GB; backing volume must be bigger
SECOND_DISK_SIZE=1280

#------------------------------------------------------------------------------
VM_MEM=1024

