./yum_init.sh
./yum_update.sh
./yum_install_mysql.sh
./install_rabbitmq.sh
./install_memcached.sh
./setup_keystone.sh
./setup_glance.sh
./setup_placement_controller.sh
./setup_nova_controller.sh
./setup_neutron_controller.sh
./setup_self-service_controller.sh
./setup_horizon.sh
./setup_cinder_controller.sh
./setup_heat_controller.sh
./setup_swift_controller.sh
