# Node VM configuration. Used by stack/wbatch (host and guest).

# Assign network interfaces to networks
NET_IF_2=dhcp
#------------------------------------------------------------------------------
# Mgmt network (elevate interface boot priority to 1; set when PXE booting)
NET_IF_0="static 10.10.0.31 1"
# Public network (select network, IP address configured manually)
NET_IF_1="manual 203.0.113.0"

